#---------------------------------------------------------------------

# Diretório de origem do backup (sem barra no final)
# Diretórios de destino do backup (sem barra no início e no final)

arr_origem[0]="/media/$USER/DISK_NAME/FOLDER_NAME"
arr_destino[0]="FOLDER_NAME"

arr_origem[1]="/home/$USER/Documentos/Contas"
arr_destino[1]="Contas"

#arr_origem[]=
#arr_destino[]=

# Unidades externas de destino (sem barra no final)
external_storage[0]="/media/$USER/DISK_NAME1/Mirror"
external_storage[1]="/media/$USER/DISK_NAME2/Mirror"

#---------------------------------------------------------------------
