#---------------------------------------------------------------------

# Diretório de origem do backup (sem barra no final)
# Diretórios de destino do backup (sem barra no início e no final)

FROM_PATH_ARR[0]="/media/$USER/DISK_NAME/FOLDER_NAME"
TO_PATH_ARR[0]="FOLDER_NAME"

FROM_PATH_ARR[1]="/home/$USER/Documentos/Contas"
TO_PATH_ARR[1]="Contas"

#FROM_PATH_ARR[]=
#TO_PATH_ARR[]=

# Unidades externas de destino (sem barra no final)
EXTERNAL_STORAGE[0]="/media/$USER/DISK_NAME1/Mirror"
EXTERNAL_STORAGE[1]="/media/$USER/DISK_NAME2/Mirror"

#---------------------------------------------------------------------
